import { ethers, artifacts } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
    console.log("Starting deployment...");

    // 1. Deploy MockUSDC
    console.log("Deploying MockUSDC...");
    const MockUSDC = await ethers.getContractFactory("MockUSDC");
    const mockUSDC = await MockUSDC.deploy();
    await mockUSDC.waitForDeployment();
    const mockUSDCAddress = await mockUSDC.getAddress();
    console.log(`MockUSDC deployed to: ${mockUSDCAddress}`);

    // 2. Deploy ConfidentialUSDC
    console.log("Deploying ConfidentialUSDC...");
    const ConfidentialUSDC = await ethers.getContractFactory("ConfidentialUSDC");
    const confidentialUSDC = await ConfidentialUSDC.deploy(mockUSDCAddress);
    await confidentialUSDC.waitForDeployment();
    const confidentialUSDCAddress = await confidentialUSDC.getAddress();
    console.log(`ConfidentialUSDC deployed to: ${confidentialUSDCAddress}`);

    console.log("Deployment Summary:");
    console.log(`MockUSDC:         ${mockUSDCAddress}`);
    console.log(`ConfidentialUSDC: ${confidentialUSDCAddress}`);

    // Save deployment info
    const deploymentsPath = path.join(__dirname, "../deployments");
    if (!fs.existsSync(deploymentsPath)) {
        fs.mkdirSync(deploymentsPath, { recursive: true });
    }

    const deploymentInfo = {
        mockUSDC: mockUSDCAddress,
        confidentialUSDC: confidentialUSDCAddress,
        network: "baseSepolia",
        timestamp: new Date().toISOString(),
    };

    fs.writeFileSync(
        path.join(deploymentsPath, "usdc.json"),
        JSON.stringify(deploymentInfo, null, 2)
    );

    console.log(`Deployment info saved to deployments/usdc.json`);

    // Update frontend constants
    const frontendUtilsPath = path.join(__dirname, "../../frontend/utils");
    const frontendAbisPath = path.join(frontendUtilsPath, "abis");

    try {
        const mockUSDCArtifact = await artifacts.readArtifact("MockUSDC");
        const confidentialUSDCArtifact = await artifacts.readArtifact("ConfidentialUSDC");

        // Create abis directory if not exists
        if (!fs.existsSync(frontendAbisPath)) {
            fs.mkdirSync(frontendAbisPath, { recursive: true });
        }

        // Write MockUSDC ABI
        const mockUSDCAbiContent = `// Auto-generated by deployUSDC.ts
export const MOCK_USDC_ABI = ${JSON.stringify(mockUSDCArtifact.abi, null, 2)} as const;
`;
        fs.writeFileSync(path.join(frontendAbisPath, "mockUSDC.ts"), mockUSDCAbiContent);

        // Write ConfidentialUSDC ABI
        const confidentialUSDCAbiContent = `// Auto-generated by deployUSDC.ts
export const CONFIDENTIAL_USDC_ABI = ${JSON.stringify(confidentialUSDCArtifact.abi, null, 2)} as const;
`;
        fs.writeFileSync(path.join(frontendAbisPath, "confidentialUSDC.ts"), confidentialUSDCAbiContent);

        // Update or create constants.ts
        const constantsPath = path.join(frontendUtilsPath, "constants.ts");
        let constantsContent = "";

        if (fs.existsSync(constantsPath)) {
            constantsContent = fs.readFileSync(constantsPath, "utf-8");
        }

        // Add USDC addresses
        const usdcConstants = `
export const MOCK_USDC_ADDRESS = "${mockUSDCAddress}";
export const CONFIDENTIAL_USDC_ADDRESS = "${confidentialUSDCAddress}";
`;

        if (constantsContent.includes("MOCK_USDC_ADDRESS")) {
            // Update existing
            constantsContent = constantsContent.replace(
                /export const MOCK_USDC_ADDRESS = "0x[a-fA-F0-9]+";/,
                `export const MOCK_USDC_ADDRESS = "${mockUSDCAddress}";`
            );
            constantsContent = constantsContent.replace(
                /export const CONFIDENTIAL_USDC_ADDRESS = "0x[a-fA-F0-9]+";/,
                `export const CONFIDENTIAL_USDC_ADDRESS = "${confidentialUSDCAddress}";`
            );
        } else {
            // Append new
            constantsContent += usdcConstants;
        }

        fs.writeFileSync(constantsPath, constantsContent);

        console.log(`Frontend files updated:`);
        console.log(`   - utils/constants.ts`);
        console.log(`   - utils/abis/mockUSDC.ts`);
        console.log(`   - utils/abis/confidentialUSDC.ts`);
    } catch (error) {
        console.error("Error updating frontend files:", error);
    }
}

main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
});
