import { ethers, artifacts } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
    console.log("Deploying ConfidentialPayroll...");

    // Read ConfidentialUSDC address from deployment
    const deploymentsPath = path.join(__dirname, "../deployments");
    const usdcDeploymentPath = path.join(deploymentsPath, "usdc.json");

    if (!fs.existsSync(usdcDeploymentPath)) {
        throw new Error(
            "USDC deployment not found! Please run deployUSDC.ts first.\n" +
            `Expected file: ${usdcDeploymentPath}`
        );
    }

    const usdcDeployment = JSON.parse(fs.readFileSync(usdcDeploymentPath, "utf-8"));
    const CONFIDENTIAL_USDC_ADDRESS = usdcDeployment.confidentialUSDC;

    console.log(`Using ConfidentialUSDC at: ${CONFIDENTIAL_USDC_ADDRESS}`);

    // Deploy ConfidentialPayroll
    const ConfidentialPayroll = await ethers.getContractFactory("ConfidentialPayroll");
    const payroll = await ConfidentialPayroll.deploy(CONFIDENTIAL_USDC_ADDRESS);
    await payroll.waitForDeployment();
    const payrollAddress = await payroll.getAddress();

    console.log(`ConfidentialPayroll deployed to: ${payrollAddress}`);

    // Save deployment info
    const deploymentInfo = {
        payroll: payrollAddress,
        confidentialUSDC: CONFIDENTIAL_USDC_ADDRESS,
        network: "baseSepolia",
        timestamp: new Date().toISOString(),
    };

    fs.writeFileSync(
        path.join(deploymentsPath, "payroll.json"),
        JSON.stringify(deploymentInfo, null, 2)
    );

    console.log(`Deployment info saved to deployments/payroll.json`);

    // Update frontend
    const frontendUtilsPath = path.join(__dirname, "../../frontend/utils");
    const frontendAbisPath = path.join(frontendUtilsPath, "abis");
    const constantsPath = path.join(frontendUtilsPath, "constants.ts");

    try {
        const payrollArtifact = await artifacts.readArtifact("ConfidentialPayroll");

        // Create abis directory if not exists
        if (!fs.existsSync(frontendAbisPath)) {
            fs.mkdirSync(frontendAbisPath, { recursive: true });
        }

        // Write PAYROLL_ABI
        const payrollAbiContent = `// Auto-generated by deployPayroll.ts
export const PAYROLL_ABI = ${JSON.stringify(payrollArtifact.abi, null, 2)} as const;
`;
        fs.writeFileSync(path.join(frontendAbisPath, "payroll.ts"), payrollAbiContent);

        // Append payroll address to constants.ts
        let constantsContent = "";
        if (fs.existsSync(constantsPath)) {
            constantsContent = fs.readFileSync(constantsPath, "utf-8");
        }

        if (constantsContent.includes("CONFIDENTIAL_PAYROLL_ADDRESS")) {
            // Update existing
            constantsContent = constantsContent.replace(
                /export const CONFIDENTIAL_PAYROLL_ADDRESS = "0x[a-fA-F0-9]+";/,
                `export const CONFIDENTIAL_PAYROLL_ADDRESS = "${payrollAddress}";`
            );
        } else {
            // Append new
            constantsContent += `export const CONFIDENTIAL_PAYROLL_ADDRESS = "${payrollAddress}";\n`;
        }

        fs.writeFileSync(constantsPath, constantsContent);

        console.log(`Frontend files updated:`);
        console.log(`   - utils/constants.ts`);
        console.log(`   - utils/abis/payroll.ts`);
    } catch (error) {
        console.error("Error updating frontend files:", error);
    }
}

main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
});
